// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHerCj8OxFLY-BKDzt8YuerAfsfDfbCEY',
    appId: '1:729729207165:web:efba46c20dbac738cf1a14',
    messagingSenderId: '729729207165',
    projectId: 'mypet-8dae1',
    authDomain: 'mypet-8dae1.firebaseapp.com',
    storageBucket: 'mypet-8dae1.appspot.com',
    measurementId: 'G-0NB723LQBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9IBqHlZfJn3Fhj5vCNvaJ0mI1VM1gEM',
    appId: '1:729729207165:android:cc4f1dccfbb1f3a6cf1a14',
    messagingSenderId: '729729207165',
    projectId: 'mypet-8dae1',
    storageBucket: 'mypet-8dae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT19MtqBZuyFLcA3eI9nl33eQgtZzdA4k',
    appId: '1:729729207165:ios:5d72f36e4c1f9bdccf1a14',
    messagingSenderId: '729729207165',
    projectId: 'mypet-8dae1',
    storageBucket: 'mypet-8dae1.appspot.com',
    iosBundleId: 'com.vetter.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT19MtqBZuyFLcA3eI9nl33eQgtZzdA4k',
    appId: '1:729729207165:ios:d4a3d53f5874f167cf1a14',
    messagingSenderId: '729729207165',
    projectId: 'mypet-8dae1',
    storageBucket: 'mypet-8dae1.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
