// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlkEO-uPdiKKIkEOHcRaH72LHKv29Yo6s',
    appId: '1:311729400938:web:381f6e10df052a31402e13',
    messagingSenderId: '311729400938',
    projectId: 'auth-8eaaf',
    authDomain: 'auth-8eaaf.firebaseapp.com',
    storageBucket: 'auth-8eaaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUzaISGd0ed-KIxcSo9KR5eI3UxrO7To',
    appId: '1:311729400938:android:470c53cfcf3d0226402e13',
    messagingSenderId: '311729400938',
    projectId: 'auth-8eaaf',
    storageBucket: 'auth-8eaaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNmshVTnuI0w1X64UR6UQtWCdguzOIqU',
    appId: '1:311729400938:ios:6e290b09765e35aa402e13',
    messagingSenderId: '311729400938',
    projectId: 'auth-8eaaf',
    storageBucket: 'auth-8eaaf.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCNmshVTnuI0w1X64UR6UQtWCdguzOIqU',
    appId: '1:311729400938:ios:b2eb3a562b032aef402e13',
    messagingSenderId: '311729400938',
    projectId: 'auth-8eaaf',
    storageBucket: 'auth-8eaaf.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
